name: ethiopian_calendar_plus
description: A comprehensive Dart package for Ethiopian Calendar conversion and formatting with Amharic language support.
version: 1.0.1
homepage: https://github.com/alexweldu123/ethiopian_calendar
repository: https://github.com/alexweldu123/ethiopian_calendar
issue_tracker: https://github.com/alexweldu123/ethiopian_calendar/issues
documentation: https://github.com/alexweldu123/ethiopian_calendar/wiki

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  meta: ^1.16.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
