name: ethiopian_calendar
description: A comprehensive Dart package for Ethiopian Calendar conversion and formatting with Amharic language support.
version: 1.0.0
homepage: https://github.com/nahom-weldu/ethiopian_calendar
repository: https://github.com/nahom-weldu/ethiopian_calendar
issue_tracker: https://github.com/nahom-weldu/ethiopian_calendar/issues
documentation: https://github.com/nahom-weldu/ethiopian_calendar/wiki

environment:
  sdk: '>=2.12.0 <4.0.0'

authors:
  - Alex Weldu <alexweldu123@gmail.com>

dependencies:
  intl: ^0.18.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
