name: ethiopian_calendar_plus
description: A comprehensive Dart package for Ethiopian Calendar conversion and formatting with Amharic language support.
version: 1.0.7
homepage: https://github.com/alexweldu123/ethiopian_calendar
repository: https://github.com/alexweldu123/ethiopian_calendar

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  meta: '>=1.15.0 <1.17.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
